### ISSUE TITLE
[Bug] Can't run whisper locally

### ISSUE THREAD

**Issue by JordieB** [JordieB/lippy#10]
```shell
$ poetry run python src/lippy/utils/listener.py
Traceback (most recent call last):
  File "/home/ubuntu/Tehas/lippy/src/lippy/utils/listener.py", line 3, in <module>
    import whisper
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/lippy-Zsiiy3EF-py3.11/lib/python3.11/site-packages/whisper/__init__.py", line 8, in <module>
    import torch
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/lippy-Zsiiy3EF-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

Seems like CUDA might be in an unexpected location and not in PATH?

**Comment by JerrickB** [comment]
Sounds like the likely issue.
[Stackoverflow](https://stackoverflow.com/questions/69779667/could-not-load-dynamic-library-libcudnn-so-8-in-ubuntu)

**Comment by JerrickB** [comment]
Whisper *can* be run locally without poetry. Since poetry is your domain, I'll leave it to you to decide if you want to fix it. For now, i have enough headaches with getting the project to run without adding this level of abstraction. Maybe we can look into implementing poetry after we get a good release.
